# Generated by Django 6.0.3 on 2026-03-31 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('credit', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('role', models.CharField(choices=[('student', 'Étudiant'), ('seller', 'Vendeur'), ('cashier', 'Responsable de caisse'), ('teacher', 'Professeur')], default='student', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cafeteria_app.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cafeteria_app.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'product', 'date')},
            },
        ),
    ]
