# Generated by Django 6.0.3 on 2026-03-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sandwich', 'Sandwich'), ('panini', 'Panini'), ('espresso', 'Espresso'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
