# Generated by Django 6.0.3 on 2026-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0002_product_category_student_is_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='has_subscriber_discount',
            field=models.BooleanField(default=False, help_text='Appliquer une réduction de 0.50€ pour les étudiants cotisants'),
        ),
    ]
