# Generated by Django 6.0.3 on 2026-03-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0003_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'product', 'date')},
        ),
    ]
